# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_build_args: "--no-build-vignettes"
r_check_args: "--no-build-vignettes --no-vignettes"

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
after_success:
  - R CMD INSTALL .
  - Rscript -e 'pkgdown::build_site()'
